### ISSUE TITLE
No jar in release

### ISSUE THREAD

**Issue by danik4985** [YTblockman/PapersPlease-ImageGenerator#2]
So I'm not sure if the dev knows, but the latest release contains no jar. This might prevent people who don't know java from using this app.

### Workaround
unfortunatelly, you need to compile the app yourself for now

fortunatelly, it is incedibly easy

1. download the source from releases
2. extract it to some folder
3. open the folder (that contains the `io` folder) in terminal/command line
4. run `javac io/hypronix/paperspleasegenerator/Main.java` - this will compile it

Now, when you want to launch it, open the folder in terminal/cmd like you did when compiling and run `java io/hypronix/paperspleasegenerator/Main`

If you're on windows, I think you should be able to create a .bat file in the folder with the following contents:
```batch
@echo off
java io/hypronix/paperspleasegenerator/Main
```
and you should be able to double click that to launch the app - not tested tho since I dont use windows

**Comment by danik4985** [comment]
note that i dont know what java version this project uses so you will probably want to use the latest version of java to make sure it will work

**Comment by YTblockman** [comment]
Should be fixed by now.
